on:
  push:
    branches: experimental

name: Deploying on shinyapps.io example

jobs:
  generate-data:
    name: update data
    runs-on: ubuntu-latest
    timeout-minutes: 75

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SHINY_ACCOUNT: ${{ secrets.SHINY_ACCOUNT }}
      SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
      SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
      
    steps:
    
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          # don't reinstall R
          install-r: false
          # use RStudio's CRAN mirror with precompiled binaries
          use-public-rspm: true
          
      - name: Install libcurl
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          
      - name: Execute tracker.R
        run: Rscript -e 'source("tracker.R")'
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m 'modifying time' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        
      - name: Deploy to shinyapps.io
        run: |
          rsconnect::setAccountInfo(name="${{secrets.SHINY_ACCOUNT}}", token="${{secrets.SHINY_TOKEN}}", secret="${{secrets.SHINY_SECRET}}")
          rsconnect::deployApp(appName = 'shiny-gha2')
        shell: Rscript {0}
        